# Generated by Django 3.0 on 2021-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=200)),
                ('sap_id', models.CharField(max_length=200)),
                ('loopback_id', models.CharField(max_length=200)),
                ('ipv4', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'router_info',
            },
        ),
    ]
